model_definition:
  framework:
#framework name and version (supported list of frameworks available at 'bx ml list frameworks')
   name: tensorflow 
   version: '1.8'
#name of the training-run
  name: audioset-classifier 
#Author name and email
  author:
    name: IBM CODAIT
    email: no-reply@us.ibm.com
  description: Audioset embedding classifier
  execution:
#Command to execute
    command: bash runme.sh 
    compute_configuration:
#Valid values for name - k80/k80x2/k80x4/p100/p100x2/v100/v100x2/small/medium/large
      name: k80
training_data_reference:b
#Source connection object credentials
  name: training-data-reference_name
  connection:
    endpoint_url: s3-api.us-geo.objectstorage.softlayer.net
    access_key_id: #Insert your access key id here.
    secret_access_key: #Insert your secret access key id here.
  source:
    bucket: training-audioset-classify
  type: s3
training_results_reference:
#Target connection object credentials
  name: training-results-reference_name
  connection:
    endpoint_url: s3-api.us-geo.objectstorage.softlayer.net
    access_key_id: #Insert your access key id here.
    secret_access_key: #Insert your secret access key id here.
  target:
    bucket: results-audioset-classify
  type: s3
